specVersion: "0.0.1"
description: "This subquery indexes kitty's birth info"
repository: "https://github.com/subquery/subql-examples"

schema: "./schema.graphql"

network:
  endpoint: "wss://node-6774223432908914688.jm.onfinality.io/ws?apikey=3a0eaba5-5331-45e1-8218-1c962d5fd802"
  types: {
    "Address": "AccountId",
    "LookupSource": "AccountId",
    "KittyIndex": "u32",
    "Kitty": "[u8; 16]"
  }

dataSources:
  - name: runtime
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleKittyCreated
          kind: substrate/EventHandler
          filter:
            module: kitties
            method: KittyCreated
        - handler: handleKittyBred
          kind: substrate/CallHandler
          filter:
            module: kitties
            method: breed
            success: true
        - handler: handleKittyTransferred
          kind: substrate/EventHandler
          filter:
            module: kitties
            method: KittyTransferred
